// Mocks generated by Mockito 5.4.4 from annotations
// in basair_real_app/test/plan_quran_completion/unit/viewmodel/quran_plan_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:basair_real_app/features/plan_quran_completion/model/contracts/quran_plan_repo.dart'
    as _i2;
import 'package:basair_real_app/features/plan_quran_completion/model/entities/quran_plan.dart'
    as _i5;
import 'package:basair_real_app/features/plan_quran_completion/view_model/providers/quran_plan_provider.dart'
    as _i4;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuranPlanRepository_0 extends _i1.SmartFake
    implements _i2.QuranPlanRepository {
  _FakeQuranPlanRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncNotifierProviderRef_1<T> extends _i1.SmartFake
    implements _i3.AsyncNotifierProviderRef<T> {
  _FakeAsyncNotifierProviderRef_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_2<T> extends _i1.SmartFake implements _i3.AsyncValue<T> {
  _FakeAsyncValue_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuranPlanNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranPlanNotifier extends _i1.Mock implements _i4.QuranPlanNotifier {
  MockQuranPlanNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuranPlanRepository get planRepo => (super.noSuchMethod(
        Invocation.getter(#planRepo),
        returnValue: _FakeQuranPlanRepository_0(
          this,
          Invocation.getter(#planRepo),
        ),
      ) as _i2.QuranPlanRepository);

  @override
  set planRepo(_i2.QuranPlanRepository? _planRepo) => super.noSuchMethod(
        Invocation.setter(
          #planRepo,
          _planRepo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AsyncNotifierProviderRef<List<_i5.QuranPlan>> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAsyncNotifierProviderRef_1<List<_i5.QuranPlan>>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i3.AsyncNotifierProviderRef<List<_i5.QuranPlan>>);

  @override
  _i3.AsyncValue<List<_i5.QuranPlan>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_2<List<_i5.QuranPlan>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AsyncValue<List<_i5.QuranPlan>>);

  @override
  set state(_i3.AsyncValue<List<_i5.QuranPlan>>? newState) =>
      super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i5.QuranPlan>> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i6.Future<List<_i5.QuranPlan>>.value(<_i5.QuranPlan>[]),
      ) as _i6.Future<List<_i5.QuranPlan>>);

  @override
  _i6.Future<List<_i5.QuranPlan>> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _i6.Future<List<_i5.QuranPlan>>.value(<_i5.QuranPlan>[]),
      ) as _i6.Future<List<_i5.QuranPlan>>);

  @override
  _i6.Future<void> addPlan(_i5.QuranPlan? plan) => (super.noSuchMethod(
        Invocation.method(
          #addPlan,
          [plan],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updatePlan(_i5.QuranPlan? plan) => (super.noSuchMethod(
        Invocation.method(
          #updatePlan,
          [plan],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deletePlan(_i5.QuranPlan? plan) => (super.noSuchMethod(
        Invocation.method(
          #deletePlan,
          [plan],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.QuranPlan?> getPlanById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPlanById,
          [id],
        ),
        returnValue: _i6.Future<_i5.QuranPlan?>.value(),
      ) as _i6.Future<_i5.QuranPlan?>);

  @override
  void listenSelf(
    void Function(
      _i3.AsyncValue<List<_i5.QuranPlan>>?,
      _i3.AsyncValue<List<_i5.QuranPlan>>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i5.QuranPlan>> update(
    _i6.FutureOr<List<_i5.QuranPlan>> Function(List<_i5.QuranPlan>)? cb, {
    _i6.FutureOr<List<_i5.QuranPlan>> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i6.Future<List<_i5.QuranPlan>>.value(<_i5.QuranPlan>[]),
      ) as _i6.Future<List<_i5.QuranPlan>>);

  @override
  bool updateShouldNotify(
    _i3.AsyncValue<List<_i5.QuranPlan>>? previous,
    _i3.AsyncValue<List<_i5.QuranPlan>>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}
